services:
  pg-database:
    image: postgres:15.3
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    networks:
      - backend
networks:
  backend:
    driver: 'bridge'
